### ISSUE TITLE
Errors while running the landslide4sense example

### ISSUE THREAD

**Issue by xen0f0n** [DeepAI4EO/Dataset4EO#2]
Hi, I've been trying to run the landslide4sense example and I've faced a few errors. I'll write down the steps I followed and how I worked around them. 

1. I logged into the [LandSlide4Sense challenge](https://www.iarai.ac.at/landslide4sense/challenge/) website to download the data. 
2. From there I downloaded 3 .zip files (TrainData.zip, ValidData.zip and TestData.zip). However, since the ```_resources``` method in the ```Landslide4Sense``` class expects the filename to be called ```landslide4sense.tar``` (from the ```_TRAIN_VAL_ARCHIVES```) I had to extract the TrainData.zip and compress it again into a .tar file named ```landslide4sense.tar```. 
3. Once I was able to run the example, I figured that by passing ```data_info=True``` I only got the paths to those .h5 files. But I wanted to get a tensor returned! So I set ```data_info=False``` 
4. Now the problem was that the code expects a path like ```landslide/landslide4sense/train/img/``` but extracting  ```landslide4sense.tar``` you end up with a folder named ```TrainData``` instead of ```train```.  Once I renamed the folder it did actually work. 

Honestly, I've been trying to work with torchgeo as well and I've faced errors there too. Since you rely on external data and you make assumptions about folder structure, with every slight change there is the risk of something breaking. (e.g. torchgeo uses Radiant MLHub to download a few datasets, and when there was a change on the mlhub side something broke). 

In my opinion, there are two approaches one can take; either 
1. host the data themselves  - and be in complete control of updating them; or 
2. write 'integrity' tests for each dataset (e.g. checking whether the hash function has changed because of a slight change on the data provider's side, or whether the folder structure/naming has changed) and having people manually making tweaks...

**Comment by tanmlh** [comment]
Many thanks for reporting this issue and giving your comments.

1. About the naming of the .zip files. You may have notised that we developed this data loading code before the official test data were released, and based on our own wrapping method of the data. As the dataset provider has updated their data, we updated our code as well to match their provided .zip files (TrainData.zip, ValidData.zip, and TestData.zip).
3. The data_info option is supposed to specify whether to return the paths or to return the tensor. But we admit that the parameter naming here is a bit confusing, we will consider to change it in the future.
4. About the data folder structure. We planned to host some of the datasets and update them (for those who have no license issue). For the others, we will have to ask the user to download them theirself. For the integrity checking part, we have updated our codes to make it work.

Thanks again for posting these issues and comments. They really help to improve our repo.

**Comment by xen0f0n** [comment]
Fantastic! Cheers!
