### ISSUE TITLE
bigearthnet download

### ISSUE THREAD

**Issue by miquel-espinosa** [DeepAI4EO/Dataset4EO#3]
Hi. I am trying to use the BigEarthNet dataset for my experiments. 
I have downloaded the tar.gz file but it is simply too big to be unziped, as it exceeds the number of folders allowed in the file system.
When extracting the file, I encounter the error `Unable to create folder: too many links`. 

Any guidance on how to deal with this error and be able to correctly use this dataset would be highly appreciated. 
Thanks in advance

**Comment by wangyi111** [comment]
Hi, thanks for your question. The 'BigEarthNet-S2-v1.0.tar.gz' consists of ~600k folders and 8M files, which seeemed to exceed the limit of your file system. 
Here we provide a link to our processed RGB images which consists of ~600k png files: check [here](https://smtaschool-my.sharepoint.com/:u:/g/personal/e3819_365e_live/EZS6uP6cZfVKoy2JpTZntZoB7Dhv6kqvqQnmAg1-muj1JQ). Hope this can solve your issue.

**Comment by miquel-espinosa** [comment]
Hi @wangyi111. Thanks!
I am able to download the RGB images correctly and load them. Would it be possible to obtain something similar for the rest of the channels (non-rgb)? I am also interested in the multispectral corresponding channels.
